"""empty message

Revision ID: 4898e518ace7
Revises: 23d557f0286d
Create Date: 2020-05-11 21:39:48.944788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4898e518ace7'
down_revision = '23d557f0286d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('links', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sent_articles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('user_subscriptions', 'created_at')
    op.drop_column('sent_articles', 'created_at')
    op.drop_column('links', 'created_at')
    op.drop_column('articles', 'created_at')
    # ### end Alembic commands ###
