"""empty message

Revision ID: 993baf91ec0e
Revises: 9e43c2e575c7
Create Date: 2020-05-18 18:56:54.336331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993baf91ec0e'
down_revision = '9e43c2e575c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['headline'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
