"""empty message

Revision ID: c668a3d03ae0
Revises: e341aed5de71
Create Date: 2020-05-29 17:21:22.674817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c668a3d03ae0'
down_revision = 'e341aed5de71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_string', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_agents')
    # ### end Alembic commands ###
