"""empty message

Revision ID: ce53fe0dc424
Revises: 993baf91ec0e
Create Date: 2020-05-18 19:37:42.107917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce53fe0dc424'
down_revision = '993baf91ec0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_headline_key', 'articles', type_='unique')
    op.create_unique_constraint(None, 'articles', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_unique_constraint('articles_headline_key', 'articles', ['headline'])
    # ### end Alembic commands ###
